name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Jekyll site.
      uses: fabacab/jekyll-builder-for-github-pages-action@v1 
    - name: Check HTML
      uses: chabad360/htmlproofer@master
      with:
       directory: "./_site"
       arguments: --allow-hash-href  --empty-alt-ignore --check_img_http 
